# Linear Algebra on Code

Last week, we saw how numerical data is represented on the computer system and how we can play with it, in a computationally useful way. This week is about linear algebra, where numbers are represented differently so that they can contribute onto the complex operations, analysis, simulation and beyond.

The numbers inside of the linear system can be represented as **vectors**. Vectors are the key elements of linear algebra that represents not only numerical data (value) but correlations between them. (characteristics, features) Let's see how we can use one of the most powerful Python library, *NumPy*, to bring Maths on paper to computers!

## Vectors

In [2]:
# Let's import all necessary libraries first.
import numpy as np

In [6]:
myfirstvector = [2, 3] # This is just a Python list
myfirstvectorspecial = np.array(myfirstvector) # If you give the Python list as a parameter of `np.array()`, it turns into something special.

In [7]:
type(myfirstvector)

list

In [8]:
type(myfirstvectorspecial)

numpy.ndarray

For faster computational processing, we will now use `NumPy` like ABCs and 123s in Data science. As you can see, we can make Python's data structure to something special with `NumPy`, so that it can handle its properties faster. For example, the most important thing is thinking about the numerical data's *shape* and *dimension*. Wait, what is a shape and a dimension in this context?

In [ ]:
# Please do + - normally only between the ones in same dimension!
mysecondvector = np.array([-1, 5])

print(myfirstvectorspecial + mysecondvector)
print(myfirstvectorspecial - mysecondvector)

[1 8]
[ 3 -2]


In [ ]:
print (-myfirstvectorspecial) # Let's inverse the vector (flipping)

[-2 -3]


In [ ]:
# scalar * vector is called 'scaling' the vector
v = np.array([1, 2, 3, 4, 5])
n = 2
print (n * v) # think about the arrow in the fifth dimension (wow)
# its length is just doubled

[ 2  4  6  8 10]


Why these are meaningful for Data science? The easiest part is calculating **mean**.

**mean** is the average value that summarises the whole data. Because it simply summarises each data, in the real world it could bring *bias*, but it is still useful and always the starting point of *descriptive statistics*. (We will revisit this in the future.)

Imagine this data.

| Street Name | House Number | House Price | 
|-------------|--------------|-------------|
| London Road | 1            | 680000      |
| London Road | 2            | 720500      |
| London Road | 3            | 500000      |

When people were calculating this on Microsoft Excel, for example, it also uses linear programming behind the scene, like this, if you want to get the mean value of house prices.

In [20]:
house_price_mean = ( np.array([1, 680000])[1] + np.array([2, 720500])[1] + np.array([3, 500000])[1] ) / 3
# Each 2D vector represents [houseNumber, housePrice] from the example.
# Mean = The sum of all data / The number of data in the target
print(house_price_mean)

633500.0


As you can see, it used the simple + - maths with vector scaling, which makes the vector three times smaller than the original one.

### These are called Linear transformation. There's more.

We just practiced scaling. And we added vectors together to make the result vector slightly rotate from the original two vectors. We also inversed the vector. (Adding a minus symbol, I mean.) These operations are all called linear transformation, and as you can see, the results are the still a vector format, which is basically a line arrow. Because there are only elements of linear properties that we deal with, this field is called 'linear algebra'.

## Dot product between matrices and vectors

A matrix is the bigger element in linear algebra that often represents the complex or collected data. Mathematically, a matrix is a transformation of unit vectors. Unit vectors, unlike the typical definition on high school textbooks such as a vector that has magnitude of 1, form each column of matrices here. When you apply the collection of unit vectors (a.k.a. matrices) to another vector, you will cause another linear transformation, which is called **dot product**.

In [23]:
# The important part of `np.array()` is... it will transform your unit vectors in a wrong way.
# It will treat your column vectors like row vectors. Think about how we define them.

unit1 = np.array([2, 3]) # When we write a code, it is a row, not a column...

In [ ]:
# Thus, if you want to construct a matrix from each unit vector, please 'transpose' it.
# 'Transpose' means you just make a row vector into a column vector, and vice versa.
unit2 = np.array([2, -1])
matrix = np.array([unit1, unit2]).transpose()
print(matrix) # It will print out the intended matrix that you wrote down on paper.

[[ 2  2]
 [ 3 -1]]


In [ ]:
# Actually, this works exactly the same if you handle the data
# like the one that you wrote down on your paper directly...
simple = np.array([[2, 2],
                  [3, -1]])
print(simple) # But there will be many different circumstances, so I would say, know both!

[[ 2  2]
 [ 3 -1]]


In [ ]:
# np.ndim() specifies the number of dimensions.
print(np.ndim(simple))
print(np.ndim(mysecondvector)) # Why 2D vector is showing the dimension 1?
# [1, 2, 3] -> This becomes 1D in NumPy and Data Science.
# Just the idiom difference between Mathematics and Computer science... Bear with me.

2
1


In [ ]:
# np.shape() specifies the number of elements along each dimension.
print(np.shape(simple))
print(np.shape(mysecondvector))

(2, 2)
(2,)


In [ ]:
another_matrix = np.array([[1, 2, 3],
                           [4, 5, 6]])
print(np.ndim(another_matrix))
print(np.shape(another_matrix)) # (how many rows?, how many columns?)

2
(2, 3)


In [ ]:
# To perform dot product, use this.
vec = np.array([2, 1])

result = matrix.dot(vec)
print(result) # See how the one on paper is printed out.

[6 5]


In [ ]:
# In the industry, rather than dot(), we use '@' or 'np.matmul()' the most.
same_result = matrix @ vec
another_same_result = np.matmul(matrix, vec)

print(same_result)
print(another_same_result)

[6 5]
[6 5]


As you can see, we are playing around with the unit vectors and the vectors that has the same dimension. All of them are mathematically 2D vectors. What if we combine the elements with different dimensions?

The result of it will **expand that vector space into fewer or more dimensions**. It means that when you **perform operations with non-square matrices** rather than square matrices, you can see there is more dynamics in your number system.

In [ ]:
cool_matrix = np.array([[1, 2, 3, 4],
                        [5, 6, 7, 8]])
cool_vector = np.array([1, 2, 3, 4])
print(cool_matrix @ cool_vector) # Dimension is got smaller, can you see?

[30 70]


In [ ]:
cool_matrix = np.array([[1, 2, 3], 
                        [5, 6, 7]])
cool_vector = np.array([1, 2, 3, 4])
print(cool_matrix @ cool_vector)

# There is an error here. Why? To perform the dot product, the number of columns in the matrix
# MUST match with the number of elements in the vector.

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 3)

## Matrix multiplication

Speaking of `np.matmul()`... What is 'matmul'? This is more advanced transformation happens in a vector space.

The specific dot product that we apply between two matrices are called matrix multiplication. How does it look on coding environment?

In [ ]:
# When you get used to Python, you can write the code more elegantly(?)...
print(np.array([[1, 2, 3],
                [4, 5, 6]])
      @ np.array([[1, 1], [2, 2], [3, 3]]))
# In this case, the number of rows and the number of columns must be matched.
# Also, the result will be the matrix of (the number of rows) x (the number of columns) from the previous two matrices, respectively.

[[14 14]
 [32 32]]


## Matrices and their properties

There are useful matrices in mathematics so mathematicians decided to call them by special names, such as an identity matrix, an inverse matrix, etc.

On the coding side, `NumPy` kindly provides the essential operations (like `@`, `np.matmul()`, `np.dot()`) so that we don't need to calculate everything by hand. Imagine you are dealing with 5 x 11 matrices with 4 x 5 matrices to calculate matrix multiplication. You will go mad.

Like we saw, **determinant** is the special property of a matrix, demonstrating how much a covered area in a vector space by certain group of unit vectors in scale after linear transformation. It is crucial for many Machine learning algorithms. It is just hidden behind the library you will use such as `sklearn` and beyond. However, that doesn't mean that you can just rely on them forever. After we know the basics, we wouldn't be afraid of any technical jargons that ML paper are saying.

Because it is super important and will be used so many time, calculating determinant on `NumPy` is straightforward.

In [39]:
from numpy.linalg import det # NumPy has special package to support Linear algebraic operations.

In [47]:
# Get the determinant of A. This is the result of scaling.
baby = np.array([[1, 0],
                 [0, 1]])
print(det(baby))
A = np.array([[2, 0],
              [0, 3]]) # 2 i-hats and 3 j-hats
print(det(A)) # Determinant grew from 1.0 to 6.0.

1.0
6.0


In [ ]:
i_hat = np.array([1, 0])
j_hat = np.array([0, 1])
# Where j-hat is sheared...
j_hat_smeared = np.array([1, 1])
basis = np.array([i_hat, j_hat]).transpose()
basis_after_smearing = np.array([i_hat, j_hat_smeared]).transpose()

print(det(basis))
print(det(basis_after_smearing))
# Smearing doesn't change the area that the unit vectors are covering, so determinant is the same.

1.0
1.0


In [ ]:
# This example is about the situation when inversion happened,
# that i-hat and j-hat swap in clockwise positions.

print(det(np.array([[-2, 1],
                    [1, 2]]))) # It makes a negative determinant.

-5.000000000000001


When you know the determinant, we can finally calculate the **inverse matrix** of the matrix. But on the coding side, of course, `NumPy` has the solution for you.

In [48]:
from numpy.linalg import inv

In [ ]:
A = np.array([[4, 2, 4],
              [5, 3, 7],
              [9, 3, 6]])
B = np.array([44, 56, 72])

# X = A's inverse * B
X = inv(A) @ B

print(X) # Thus, following the solution, x = 2, y = 34, z = -8

[ 2. 34. -8.]


In [53]:
print(inv(A))

[[-5.00000000e-01  9.86864911e-17  3.33333333e-01]
 [ 5.50000000e+00 -2.00000000e+00 -1.33333333e+00]
 [-2.00000000e+00  1.00000000e+00  3.33333333e-01]]


In [ ]:
# Calculating n x n matrices' inverse is complicated, but the computer will do the job for you.
tricky = np.array([[3, 0, 2],
                   [2, 0, -2],
                   [0, 1, 1]])
print(det(tricky))
print(inv(tricky)) # You can try calculate this on paper using Gauss-Jordan method.

10.000000000000002
[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


## Eigenvalues and eigenvector

Now we can finally learn eigenvalues and eigenvector, which are crucial members of numerous machine learning tasks, such as linear regression.

This is one of the most trickiest part to understand the pure calculation. But if you practice simultaneous equation and factorisation, it is doable. However, during the real-world machine learning tasks, of course we cannot calculate everything by hand. However, we must know the basic things so that we don't rely on the black box of borrowing libraries.

In [54]:
# On the code library, NumPy will do everything for you.
from numpy.linalg import eig

In [ ]:
A = np.array([[-6, 3],
              [4, 5]])

eigenvalues, eigenvectors = eig(A)
print(f'eigenvalues: {eigenvalues}')
print(f'eigenvectors: {eigenvectors}')

eigenvalues: [-7.+0.j  6.+0.j]
eigenvectors: [[-0.9486833 +0.j -0.24253563+0.j]
 [ 0.31622777+0.j -0.9701425 +0.j]]


Sometimes there is a complex number of eigenvalues and eigenvector elements. Look at the `j` symbol. Because `i` in coding normally used for iteration (`for` loop) or indicating indicies, rather than the real definition of complex number, `j` is used.

In [56]:
# c.f. Identity matrix
i = np.identity(2) # creating 2x2 identity matrix
print(i)

[[1. 0.]
 [0. 1.]]
